# Goal
float64 max_pressure
float64 min_pressure
bool    advanced
bool    auto_release
---
# Result
uint32  UNKNOWN_OBJECT=0
uint32  REACHED_MAX_PRESSURE=1
uint32  REACHED_MIN_PRESSURE=2
uint32  NO_OBJECT=3

float64 pressure
uint32  reached_goal
---
# Feedback
float64 pressure
uint32  reached_goal
