uint8 rACT  # activate (0: deactivate, 1: activate)
uint8 rMOD  # gripper mode (0: automatic, 1: advanced, 2,3: reserved)
uint8 rGTO  # go-to (0: stop vacuum generator, 1: follow requested vacuum value)
uint8 rATR  # auto-release (0: normal, 1: emergency slow move)
uint8 rPR   # maximum vacuum/pressure request in manual/automatic mode
uint8 rSP   # action timeout
uint8 rFR   # minimum vacuum/pressure request
