$(arg prefix)robotiq_85_controller:
  gripper_action:
    type: aist_robotiq_controller/RobotiqGripperController

    l_gripper_joint: $(arg prefix)gripper_finger_joint
    r_gripper_joint: $(arg prefix)gripper_right_inner_finger_joint

    ur_script_topic: /$(arg prefix)controller/ur_driver/URScript
    ur_state_topic:  /$(arg prefix)controller/ur_driver/robot_mode_state

    # ur_script_filepath: ros::package::getPath("aist_robotiq")+"/src/urscript/robotiq_urscript.script")
    # moving_duration:
    #   short: 1.0
    #   long:  4.0

    # Feedback rate in Hz
    publish_rate: 100
    min_gap_counts: 224
    # Gripper width in meters [0, 0.085]
    min_gap:    0.0
    max_gap:    0.085
    # Gripper speed in m/s [0.013, 0.1]
    min_speed:  0.013
    max_speed:  0.1
    # Gripper force in N. [40, 100]
    min_force:  40.0
    max_force:  100.0

gazebo:
  $(arg prefix)gripper_finger_joint:
    position:
      p: 5000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
