joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

$(arg prefix)robotiq_140_controller:
  gripper_action:
#    type: aist_robotiq/RobotiqGripperController
    type: robot_controllers/ParallelGripperController

    l_gripper_joint: $(arg prefix)gripper_finger_joint
    r_gripper_joint: $(arg prefix)gripper_right_inner_finger_joint

    ur_script_topic: /$(arg prefix)controller/ur_driver/URScript
    ur_state_topic:  /$(arg prefix)controller/ur_driver/robot_mode_state

    # ur_script_filepath: ros::package::getPath("aist_robotiq")+"/src/urscript/robotiq_urscript.script")
    # moving_duration:
    #   short: 1.0
    #   long:  4.0

    # Feedback rate in Hz
    publish_rate: 100
    min_gap_counts: 224
    # Gripper width in meters [0, 0.140]
    min_gap:   0.0
    max_gap:   0.140
    # Gripper speed in m/s [0.03, 0.25]
    min_speed: 0.03
    max_speed: 0.25
    # Gripper force in N. [10, 125]
    min_force: 10.0
    max_force: 125.0

gazebo:
  default_controllers:
    - $(arg prefix)robotiq_140_controller/gripper_action

  $(arg prefix)gripper_finger_joint:
    position:
      p: 5000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
