<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="robotiq_arg2f_coupling" params="prefix parent *origin">

    <xacro:property name="coupling_radius" value="0.0375"/>
    <xacro:property name="coupling_length" value="0.0169"/>

    <link name="${prefix}base_link">
      <inertial>
        <origin xyz="8.625E-08 -4.6583E-06 0.03145" rpy="0 0 0" />
        <mass value="0.22652" />
        <inertia ixx="0.00020005" ixy="-4.2442E-10" ixz="-2.9069E-10" iyy="0.00017832" iyz="-3.4402E-08" izz="0.00013478" />
      </inertial>
      <visual>
        <origin xyz="${coupling_length/2} 0 0" rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
          <mesh filename="package://aist_robotiq/meshes/visual/robotiq_arg2f_coupling.stl"
		scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.1 0.1 0.1 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="${coupling_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder length="${coupling_length}" radius="${coupling_radius}"/>
        </geometry>
        <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
        <!-- <geometry> -->
        <!--   <mesh filename="package://aist_robotiq/meshes/collision/robotiq_arg2f_coupling.stl" /> -->
        <!-- </geometry> -->
      </collision>
    </link>
    <gazebo reference="${prefix}base_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- Add the force sensor in front of the gripper. -->
    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${prefix}base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <link name="${prefix}flange_link"/>
    <joint name="${prefix}flange_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}flange_link"/>
      <origin xyz="${coupling_length} 0 0" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>
