id:                  InstalledExamples-basic-example
trigger_mode:        0
intensity_scale:     0.5
frame:               phoxi_sensor
rate:                20
point_format:        1
send_point_cloud:    true
send_normal_map:     true
send_depth_map:      true
send_confidence_map: false
send_texture:        true
