id:                        InstalledExamples-basic-example
trigger_mode:              0
intensity_scale:           0.5
rate:                      20.0
normals_estimation_radius: 2
send_point_cloud:          true
send_normal_map:           true
send_depth_map:            true
send_confidence_map:       false
send_texture:              true
