# Gripper joint position in radians [0.03, 0,00]
min_joint_position: 0.03
max_joint_position: 0.00

# Gripper width in meters [0, 0.026]
min_position: 0.000
max_position: 0.026

# Gripper velocity in m/s [0.020, 0.150]
min_velocity: 0.020
max_velocity: 0.150

# Gripper effort in N. [20.0, 185.0]
min_effort:  20.0
max_effort: 185.0

# Joint name
joint_name: $(arg prefix)joint_finger
